/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IndexingRouteImport } from './routes/indexing'
import { Route as KeywordsRouteImport } from './routes/keywords'
import { Route as MetaRulesRouteImport } from './routes/meta-rules'
import { Route as PagesRouteImport } from './routes/pages'
import { Route as PerformanceRouteImport } from './routes/performance'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexingRoute = IndexingRouteImport.update({
  id: '/indexing',
  path: '/indexing',
  getParentRoute: () => rootRouteImport,
} as any)
const KeywordsRoute = KeywordsRouteImport.update({
  id: '/keywords',
  path: '/keywords',
  getParentRoute: () => rootRouteImport,
} as any)
const MetaRulesRoute = MetaRulesRouteImport.update({
  id: '/meta-rules',
  path: '/meta-rules',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesRoute = PagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/indexing': typeof IndexingRoute
  '/keywords': typeof KeywordsRoute
  '/meta-rules': typeof MetaRulesRoute
  '/pages': typeof PagesRoute
  '/performance': typeof PerformanceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/indexing': typeof IndexingRoute
  '/keywords': typeof KeywordsRoute
  '/meta-rules': typeof MetaRulesRoute
  '/pages': typeof PagesRoute
  '/performance': typeof PerformanceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/indexing': typeof IndexingRoute
  '/keywords': typeof KeywordsRoute
  '/meta-rules': typeof MetaRulesRoute
  '/pages': typeof PagesRoute
  '/performance': typeof PerformanceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/indexing' | '/keywords' | '/meta-rules' | '/pages' | '/performance'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/indexing' | '/keywords' | '/meta-rules' | '/pages' | '/performance'
  id:
    | '__root__'
    | '/'
    | '/indexing'
    | '/keywords'
    | '/meta-rules'
    | '/pages'
    | '/performance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IndexingRoute: typeof IndexingRoute
  KeywordsRoute: typeof KeywordsRoute
  MetaRulesRoute: typeof MetaRulesRoute
  PagesRoute: typeof PagesRoute
  PerformanceRoute: typeof PerformanceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indexing': {
      id: '/indexing'
      path: '/indexing'
      fullPath: '/indexing'
      preLoaderRoute: typeof IndexingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keywords': {
      id: '/keywords'
      path: '/keywords'
      fullPath: '/keywords'
      preLoaderRoute: typeof KeywordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meta-rules': {
      id: '/meta-rules'
      path: '/meta-rules'
      fullPath: '/meta-rules'
      preLoaderRoute: typeof MetaRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages': {
      id: '/pages'
      path: '/pages'
      fullPath: '/pages'
      preLoaderRoute: typeof PagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IndexingRoute: IndexingRoute,
  KeywordsRoute: KeywordsRoute,
  MetaRulesRoute: MetaRulesRoute,
  PagesRoute: PagesRoute,
  PerformanceRoute: PerformanceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
