/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexingRouteImport } from './routes/indexing'
import { Route as IssuesRouteImport } from './routes/issues'
import { Route as KeywordsRouteImport } from './routes/keywords'
import { Route as MetaRulesRouteImport } from './routes/meta-rules'
import { Route as PagesRouteImport } from './routes/pages'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as TechnicalRouteImport } from './routes/technical'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexingRoute = IndexingRouteImport.update({
  id: '/indexing',
  path: '/indexing',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesRoute = IssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const KeywordsRoute = KeywordsRouteImport.update({
  id: '/keywords',
  path: '/keywords',
  getParentRoute: () => rootRouteImport,
} as any)
const MetaRulesRoute = MetaRulesRouteImport.update({
  id: '/meta-rules',
  path: '/meta-rules',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesRoute = PagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicalRoute = TechnicalRouteImport.update({
  id: '/technical',
  path: '/technical',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/indexing': typeof IndexingRoute
  '/issues': typeof IssuesRoute
  '/keywords': typeof KeywordsRoute
  '/meta-rules': typeof MetaRulesRoute
  '/pages': typeof PagesRoute
  '/performance': typeof PerformanceRoute
  '/reports': typeof ReportsRoute
  '/technical': typeof TechnicalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/indexing': typeof IndexingRoute
  '/issues': typeof IssuesRoute
  '/keywords': typeof KeywordsRoute
  '/meta-rules': typeof MetaRulesRoute
  '/pages': typeof PagesRoute
  '/performance': typeof PerformanceRoute
  '/reports': typeof ReportsRoute
  '/technical': typeof TechnicalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/indexing': typeof IndexingRoute
  '/issues': typeof IssuesRoute
  '/keywords': typeof KeywordsRoute
  '/meta-rules': typeof MetaRulesRoute
  '/pages': typeof PagesRoute
  '/performance': typeof PerformanceRoute
  '/reports': typeof ReportsRoute
  '/technical': typeof TechnicalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/indexing'
    | '/issues'
    | '/keywords'
    | '/meta-rules'
    | '/pages'
    | '/performance'
    | '/reports'
    | '/technical'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/indexing'
    | '/issues'
    | '/keywords'
    | '/meta-rules'
    | '/pages'
    | '/performance'
    | '/reports'
    | '/technical'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/indexing'
    | '/issues'
    | '/keywords'
    | '/meta-rules'
    | '/pages'
    | '/performance'
    | '/reports'
    | '/technical'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  IndexingRoute: typeof IndexingRoute
  IssuesRoute: typeof IssuesRoute
  KeywordsRoute: typeof KeywordsRoute
  MetaRulesRoute: typeof MetaRulesRoute
  PagesRoute: typeof PagesRoute
  PerformanceRoute: typeof PerformanceRoute
  ReportsRoute: typeof ReportsRoute
  TechnicalRoute: typeof TechnicalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indexing': {
      id: '/indexing'
      path: '/indexing'
      fullPath: '/indexing'
      preLoaderRoute: typeof IndexingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues': {
      id: '/issues'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof IssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keywords': {
      id: '/keywords'
      path: '/keywords'
      fullPath: '/keywords'
      preLoaderRoute: typeof KeywordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meta-rules': {
      id: '/meta-rules'
      path: '/meta-rules'
      fullPath: '/meta-rules'
      preLoaderRoute: typeof MetaRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages': {
      id: '/pages'
      path: '/pages'
      fullPath: '/pages'
      preLoaderRoute: typeof PagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technical': {
      id: '/technical'
      path: '/technical'
      fullPath: '/technical'
      preLoaderRoute: typeof TechnicalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  IndexingRoute: IndexingRoute,
  IssuesRoute: IssuesRoute,
  KeywordsRoute: KeywordsRoute,
  MetaRulesRoute: MetaRulesRoute,
  PagesRoute: PagesRoute,
  PerformanceRoute: PerformanceRoute,
  ReportsRoute: ReportsRoute,
  TechnicalRoute: TechnicalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
